In [2]:
import numpy as np

In [3]:
print(np.array([1,2,3,4])[-1])

4


In [52]:
arr = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
# np.shape(arr)
# arr.shape
# arr.ndim
np.average(arr)

np.float64(5.0)

In [53]:
a = np.array([[1, 2, 3], [4, 2, 6]])
2 in a

True

In [42]:
a[0,:]

array([1, 0, 3])

In [20]:
a.transpose()


array([[1, 0],
       [0, 2],
       [3, 3]])

In [5]:
print(np.array([1,2,3,4,5,6]).reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [24]:
a = np.random
n = 5
array = np.random.randint(1,10,size=n*n)
array = array.reshape((n,n))
print (array.mean(axis=1))
array


[2.8 5.8 5.8 6.2 4.6]


array([[3, 6, 1, 2, 2],
       [3, 9, 8, 4, 5],
       [4, 4, 8, 4, 9],
       [2, 5, 7, 9, 8],
       [2, 4, 2, 8, 7]])

In [58]:
np.array(18, 14, 23, 36)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [61]:
arr1 = np.array([[1, 2, 3], [4, 2, 6]])
arr2 = np.array([[1, 2, 3], [4, 2, 6]])


In [78]:
x = np.array([1,2,3])
y = np.array([1,2,3])

In [79]:
np.linalg.norm(x-y)

np.float64(0.0)

In [81]:
import numpy as np

def mnk(x_, y_):
A = np.vstack([x_, np.ones(len(x_))]).T
a, b = np.linalg.lstsq(A, y_, rcond=None)[0]



x = np.linspace(0, 10, 30)
a = 2
b = 1
y = a*x + b

a_mnk, b_mnk = mnk(x, y)

print("Коэффициенты a и b:", a_mnk, b_mnk)

IndentationError: expected an indented block after function definition on line 3 (3263047616.py, line 4)