# Основы линейной алгебры в Numpy

In [ ]:
# Импортируем нужные библиотеки
import numpy as np

## Векторы

In [15]:
# вектор-строка
a = np.array([0, 1, 2, 3, 4])
print(f'Размерность вектора {a.shape}')
a

Размерность вектора (5,)


array([0, 1, 2, 3, 4])

In [18]:
a.size

5

In [19]:
# вектор-столбец
a = np.array([[0], [1], [2], [3], [4]])
print(f'Размерность вектора {a.shape}')
a

Размерность вектора (5, 1)


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
# Количество объектов
a.size

5

In [21]:
# аналог range
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(10, 5, -2)

array([10,  8,  6])

In [23]:
# возвращает числа равноудаленные в заданном интервале
np.linspace(0, 10, num=17)

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ,  3.125,  3.75 ,  4.375,
        5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   ])

In [ ]:
np.linspace(0, 1, num=5)

In [ ]:
z = np.zeros(10, dtype='int')
# z = np.zeros(10)
z

In [ ]:
z.dtype

In [ ]:
o = np.ones(5, dtype='int')
o

In [ ]:
o.dtype = 'int'
print(o)
o.dtype

In [ ]:
oo = np.zeros_like(o)
oo.append(10)

In [ ]:
o[1:3] = 10
o

In [ ]:
np.where(o == 10)

In [ ]:
o

In [ ]:
np.where(o != 1, 2, o)

## Матрицы

In [ ]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]])
a.shape

In [ ]:
# Количество объектов
a.size

In [ ]:
A = np.array([[1, 2],
              [6, 3]])
A / 2

In [ ]:
A.shape

In [ ]:
A.reshape(1, -1).shape

In [ ]:
A

In [ ]:
A.resize(4)

In [ ]:
A

In [ ]:
A = np.array([[1, 2],
              [6, 3]])
A + 2

In [ ]:
A * 2

### Математика с несколькими матрицами

In [ ]:
A = np.array([[1, 2],
              [6, 3]])

B = np.array([[0, 4],
              [0, 2]])

# сложение матриц
A + B

In [ ]:
# поэлементное переменожение матриц
A * B

In [ ]:
# матричное переменожение (строка на столбец)
A @ B
A.dot(B)
np.dot(A, B)

In [ ]:
# строка на столбец
print(f'Первая строка {A[0]}')
print(f'Первый столбец {B[:, 0]}')

A[0] * B[:, 0]

In [ ]:
# строка на столбец
print(f'Первая строка {A[0]}')
print(f'Второй столбец {B[:, 1]}')
A[0] * B[:, 1]

In [ ]:
# для перемножения матриц нужно, чтобы кол-во столбцов совпадало с кол-вом строк
A.shape, B.shape

In [ ]:
A = np.array([[1, 2],
              [6, 3]])

C = np.array([[0, 1],
              [0, 3],
              [9, 3]])
A @ C

In [ ]:
A.shape, C.shape

In [ ]:
# конкатенация массивов
np.concatenate([A, C[:2]], axis=1)

In [ ]:
np.linalg.det(A)

### Получение статистик

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a

**Среднее арифметическое**

In [ ]:
mean = a.sum() / len(a)
mean

**Дисперсия и стандартное отклонение**

*Дисперсия* - это показатель вариации, который представляет собой средний квадрат отклонений от математического ожидания (среднее арифметическое). Она выражает разброс чисел относительно среднего значения.

*Стандартное отклонение* (среднеквадратичное отклонение) - это величина, характеризующая разброс данных относительно среднего значения.

In [ ]:
a - mean

In [ ]:
variance = np.mean((a - mean) ** 2)
std = np.sqrt(variance)
variance, std

Подсчет с помощью numpy

In [ ]:
mean_np = np.mean(a)
mean_np

In [ ]:
std_np = np.std(a)
std_np

In [ ]:
np.var(a)

**Медиана**

*Медиана* - значение, которая делит его на две равные части или же проще говоря, это середина отсортированной выборки.

In [ ]:
a = [3, 4, 5, 6, 1, 2, 2, 6]
a = np.sort(a)
a

In [ ]:
len(a)

In [ ]:
np.median(a)

**Квантили**

*Квартили* - это значения, которые делят выборку на 4 равные (по количеству объектов) части.
Откуда следует, что вторая квартиль - это медиана.


КваНтиль 50% = КваРтиль 2 = медиана

In [ ]:
np.quantile(a, 0.5)

In [ ]:
np.median(a)

КваНтиль 25% = КваРтиль 1

In [ ]:
a

In [ ]:
np.quantile(a, q=0.25)

КваНтиль 75% = КваРтиль 3

In [ ]:
np.quantile(a=a, q=0.75)

**Мода**

Мода - это объект с максимальной частотой или проще говоря, самый популярный (частовстречаемый) объект в выборке.

In [ ]:
a

In [ ]:
import pandas as pd

pd.Series(a).mode()

#### Статистики на примере

In [ ]:
np.random.seed(1)
salary1 = np.random.randint(10000, 80000, size=400)
salary2 = np.random.randint(1e6, 1e7, size=5)
salary = np.r_[(salary1, salary2)]

pd.Series(salary).hist();

In [ ]:
salary.min(), salary.max()

In [ ]:
salary.mean()

In [ ]:
np.median(salary)

In [ ]:
np.where(salary > np.median(salary))[0].shape

In [ ]:
np.std(salary)

In [ ]:
np.quantile(salary, q=0.5)

In [ ]:
np.quantile(salary, q=0.25)

In [ ]:
np.quantile(salary, q=0.75)

In [ ]:
np.quantile(salary, q=0.01)

In [ ]:
pd.Series(salary).mode()

In [ ]:
pd.Series(salary).value_counts()

#### С матрицами

In [ ]:
np.sum(A) / A.size

In [ ]:
A[:, 0].sum() / A[:, 0].size  # axis=0

In [ ]:
A[:, 1].sum() / A[:, 1].size  # axis=0

In [ ]:
A[0].sum() / A[0].size, A[1].sum() / A[1].size  # axis=1

In [ ]:
print(f'Среднее по всему массиву {np.mean(A)}')
print(f'Среднее по столбцам {np.mean(A, axis=0)}')
print(f'Среднее по строкам {np.mean(A, axis=1)}')

### Модуль random в numpy

In [ ]:
np.random.seed(1)  # фиксация случайности
np.random.randint(0, 5, size=3)

In [24]:
np.random.randn(2, 5)

array([[ 0.79795396,  0.36929797, -0.70694245, -0.29535402, -0.10362975],
       [-0.15295427, -0.43533704,  0.13624039, -0.98899325, -1.54270799]])

In [ ]:
np.random.choice(np.array([2, 1, 3, 4]), size=3, replace=False)

In [ ]:
np.random.choice(
    ['white', 'black', 'red', 'blue'],
    size=2,
    replace=False)

### 🧠 Упражнение: поиск среднего значение в строках

Создайте двумерный массив numpy размером 5x5, заполненный случайными целыми числами от 1 до 10. Найдите среднее значение каждой строки и выведите результат.


#### 🧠 Упражнение: поиск среднего значение в строках (ответ)

Создайте двумерный массив numpy размером 5x5, заполненный случайными целыми числами от 1 до 10. Найдите среднее значение каждой строки и выведите результат.


In [26]:
np.random.seed(1)

n = 5
array = np.random.randint(1, 10, size=n*n)
array = array.reshape((n, n))
array.mean(axis=1)

array([4.6, 5. , 4.4, 5.4, 5. ])

In [ ]:
array

In [ ]:
array[0].mean(), array[1].mean()

### 🧠 Упражнение: замена столбца на среднее


Создайте двумерный массив numpy размером 6x6, заполненный случайными числами. Найдите среднее значение каждого столбца и замените все элементы столбца на это среднее значение.

#### 🧠 Упражнение: замена столбца на среднее (ответ)


In [ ]:
np.random.seed(1)

n = 6
array = np.random.randint(1, 10, size=n*n)
array = array.reshape((n, n))
mean_values = array.mean(axis=0)

In [ ]:
array

In [ ]:
array[:, 0].mean(), array[:, 1].mean()

In [ ]:
array.dtype = 'float'
array.dtype

In [ ]:
for i in range(array.shape[1]):
    array[:, i] = mean_values[i]

array

## Векторы в пространстве

In [ ]:
import matplotlib.pyplot as plt

vec0 = np.array([0, 1])
vec1 = np.array([5, 0])


plt.figure(figsize=(8, 6))

for i, vector in enumerate([vec0, vec1]):
    plt.plot([0, vector[0]], [0, vector[1]], label=f'{i} vector')

plt.legend();

In [ ]:
# найти гипотенузу прямоугольника
# a^2 + b^2 = c^2

((5 - 0) ** 2 + (1 - 0) ** 2) ** 0.5

In [ ]:
vec0 - vec1

In [ ]:
np.sqrt(((vec0 - vec1) ** 2).sum())

In [ ]:
np.linalg.norm(vec0 - vec1, ord=1)

## Применение numpy массивов

In [ ]:
import matplotlib.pyplot as plt
import requests
import cv2


response = requests.get('https://web-zoopark.ru/wp-content/uploads/2018/07/7-9.jpg')
response

In [ ]:
img_bytes = response.content
img_bytes

In [ ]:
np.frombuffer(img_bytes, np.uint8)

In [ ]:
img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), -1)
plt.imshow(img);

In [ ]:
img

In [ ]:
img.shape

BGR -> RGB

In [ ]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img);

In [ ]:
img

In [ ]:
img.shape

In [ ]:
print(f'Высота {img.shape[0]}')
print(f'Ширина {img.shape[1]}')
print(f'Количество каналов {img.shape[2]}')

In [ ]:
x_min, x_max = 400, 900
y_min, y_max = 200, 600

crop_img = img[y_min:y_max, x_min:x_max]
print('Срез фотки', crop_img.shape)
plt.imshow(crop_img);

In [ ]:
cv2.imwrite('img.jpeg', crop_img)

In [ ]:
crop_img = cv2.imread('img.jpeg')
plt.imshow(crop_img);

In [ ]:
crop_img.shape

In [ ]:
crop_img = cv2.resize(crop_img, (1000, 800))
plt.imshow(crop_img);

In [ ]:
crop_img.shape

### 🧠 Упражнение: объединение изображений

Загрузите два изображения с помощью библиотеки OpenCV и преобразуйте их в массивы numpy. Объедините эти два массива в один, используя операции numpy, и сохраните полученный массив как новое изображение.

Если у изображений разный размер, отмасштабируйте изображения до одного размера (через `cv2.resize`)

In [ ]:
!wget 'https://laplaya-rus.ru/wp-content/uploads/4/3/8/4382527fd4dbee20bc240764919f8c12.jpeg' -O img1.jpeg
!wget 'https://laplaya-rus.ru/wp-content/uploads/5/b/8/5b8316fc1354f9a8be2a3506942850c1.jpeg' -O img2.jpeg

#### 🧠 Упражнение: объединение изображений (ответ)


In [ ]:
img1 = cv2.imread('img1.jpeg')
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
img1.shape

In [ ]:
img2 = cv2.imread('img2.jpeg')
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
img2.shape

In [ ]:
img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))

In [ ]:
img = np.concatenate([
    img1,
    img2
])

plt.imshow(img);

# Система рекомендаций

## Подготовка данных

In [ ]:
# Источник и описание полей датасета: http://archive.ics.uci.edu/ml/datasets/online+retail#

In [ ]:
# Импортируем нужные библиотеки
import pandas as pd

In [ ]:
%%time
# Загружаем и читаем датасет
df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')
# df = pd.read_excel('OnlineRetail.xlsx')
df.head()

In [ ]:
# Смотрим размеры датасета
df.shape

In [ ]:
df[df['Quantity'] <= 0]

In [ ]:
# Чистим датасет: удаляем записи с нулевыми покупками
df = df[df['Quantity'] > 0]

In [ ]:
df.isna().sum()

In [ ]:
# Чистим датасет: удаляем записи с пропусками в customer_id
df = df.dropna(subset=['CustomerID'])

In [ ]:
df.isna().sum()

In [ ]:
df['CustomerID'] = df['CustomerID'].astype('int')

In [ ]:
# Агрегируем данные в сводную таблицу "покупатель - товар"
customer_item_matrix = df.pivot_table(
    index='CustomerID',
    columns='StockCode',
    values='Quantity',
    aggfunc='sum'
)

customer_item_matrix.head()

In [ ]:
# Смотрим на размеры таблицы
customer_item_matrix.shape

In [ ]:
# Сравниваем кол-во строк с кол-вом уникальных покупателей в исходном датафрейме
df['CustomerID'].nunique()

In [ ]:
# Сравниваем кол-во столбцов с кол-вом уникальных товаров в исходном датафрейме
df['StockCode'].nunique()

In [ ]:
# Заменяем кол-во покупок на событие: 1 - факт покупки, 0 - отсутствие покупки
customer_item_matrix = customer_item_matrix.map(lambda x: 1 if x > 0 else 0)
customer_item_matrix.head()

## Коллаборативная фильтрация (Collaborative Filtering)

<img src='https://repository-images.githubusercontent.com/107717770/e1dfeb9b-ac36-4a49-8150-d6136705186b'>

Ссылка на изображение: https://repository-images.githubusercontent.com/107717770/e1dfeb9b-ac36-4a49-8150-d6136705186b

In [ ]:
# Импортируем библиотеку для создания разреженной матрицы
from scipy.sparse import csr_matrix

In [ ]:
n = np.array([[1, 0.5, 0],
              [3, 0, 5],
              [0, 5, 0]])

In [ ]:
csr_n = csr_matrix(n)  # sparse matrix
csr_n

In [ ]:
print(csr_n)

In [ ]:
csr_n.data

In [ ]:
csr_n.indices

In [ ]:
csr_n.toarray()

<table>
<tr>
<td>
<img src='https://drive.google.com/uc?export=view&id=1TrLSown1yxEswyJd_PeBl3yjnzioKTuQ' width=400>
</td>
<td>
<img src='https://drive.google.com/uc?export=view&id=1FbARc1vHbEURgDlwY_qkaq2YWRLFk8db' width=400>
</td>
</tr>
</table>

In [ ]:
# Задаем функцию расчета косинуса между векторами-строками покупателей
def cos_sim(array):
    # преобразуем
    csr_array = csr_matrix(array)
    numerator = np.dot(csr_array, csr_array.T).toarray()
    denomenator = np.linalg.norm(array, axis=1, keepdims=True) * np.linalg.norm(array.T, axis=0, keepdims=True)
    return numerator / denomenator

In [ ]:
# A

In [ ]:
# np.linalg.norm(A, axis=1, keepdims=True)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

for i, vector in enumerate(n):
    plt.plot([0, vector[0]], [0, vector[1]], label=f'{i} vector')

plt.legend();

In [ ]:
n[0], n[1], n[2]

In [ ]:
# Вычисляем косинусную меру сходства между векторами-строками игрушечного массива
cos_sim(n)

In [ ]:
# Преобразуем исходную матрицу "покупатель - товар" в массив numpy
m = customer_item_matrix.values
m

In [ ]:
# Вычисляем косинусную меру сходства между векторами-строками покупателей
user_user_sim_matrix = cos_sim(m)
user_user_sim_matrix

In [ ]:
# Добавляем название столбцов и индексов в матрицу мер близости между векторами-строками покупателей
user_user_sim_matrix = pd.DataFrame(user_user_sim_matrix)

user_user_sim_matrix.columns = customer_item_matrix.index

user_user_sim_matrix['CustomerID'] = customer_item_matrix.index
user_user_sim_matrix = user_user_sim_matrix.set_index('CustomerID')

user_user_sim_matrix.head()

## Рекомендации на основе коллаборативной фильтрации

In [ ]:
# На примере эталонного покупателя находим тех покупателей, которые близки к нему по косинусной мере
user_user_sim_matrix.loc[12350].sort_values(ascending=False)

In [ ]:
# customer_item_matrix

In [ ]:
# Определяем перечень уникальных покупок нашего эталонного покупателя
A = customer_item_matrix.loc[12350]
items_bought_by_A = A[A > 0].index.tolist()
items_bought_by_A

In [ ]:
# Определяем перечень уникальных покупок покупателя наиболее близкого к нашему
B = customer_item_matrix.loc[17935]
items_bought_by_B = B[B > 0].index.tolist()
items_bought_by_B

In [ ]:
# Отбираем те покупки, которые есть у близкого к нашему покупателю, но нет у нашего покупателя
items_to_recommend_to_A = set(items_bought_by_B) - set(items_bought_by_A)
items_to_recommend_to_A

In [ ]:
# Выводим перечень товаров, рекомендованных для нашего эталонного покупателя
df[df['StockCode'].isin(items_to_recommend_to_A)][['StockCode', 'Description']].drop_duplicates().set_index('StockCode')

### 🧠 Упражнение: item_based коллаборативная фильтрация

1. Используйте датасет с  текущего урока.
2. Создайте матрицу item-customer (по строкам - товары, по столбцам - покупатели)
3.Проведите оценку мер близости товаров, получив матрицу item_item_sim_matrix со значениями косинусов между векторами товаров.
4. Отберите ТОП-10 похожих товаров по StockCode. 23166
5. Выведите список ТОП-10 похожих товаров с названиями (Description) на экран.

#### 🧠 Упражнение: item_based коллаборативная фильтрация (ответ)


In [ ]:
# Импортируем нужные библиотеки
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix

In [ ]:
%%time
# Загружаем и читаем датасет
df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')
# df = pd.read_excel('OnlineRetail.xlsx')
df.head()

In [ ]:
# Чистим датасет: удаляем записи с нулевыми покупками
df = df[df['Quantity'] > 0]

# Чистим датасет: удаляем записи с пропусками в customer_id
df = df.dropna(subset=['CustomerID'])
df['CustomerID'] = df['CustomerID'].astype('int')

In [ ]:
# Агрегируем данные в сводную таблицу "товар - покупатель"
item_customer_matrix = df.pivot_table(
    index='StockCode',
    columns='CustomerID',
    values='Quantity',
    aggfunc='sum'
)

item_customer_matrix.head()

In [ ]:
# Заменяем кол-во покупок на событие: 1 - факт покупки, 0 - отсутствие покупки
item_customer_matrix = item_customer_matrix.applymap(lambda x: 1 if x > 0 else 0)
item_customer_matrix.head()

In [ ]:
# Задаем функцию расчета косинуса между векторами-строками покупателей
def cos_sim(array):
    # преобразуем
    csr_array = csr_matrix(array)
    numerator = np.dot(csr_array, csr_array.T).toarray()
    denomenator = np.linalg.norm(array, axis=1, keepdims=True) * np.linalg.norm(array.T, axis=0, keepdims=True)
    return numerator / denomenator

In [ ]:
# Преобразуем исходную матрицу "товар - покупатель" в массив numpy
m = item_customer_matrix.values
m

In [ ]:
# Вычисляем косинусную меру сходства между векторами-строками товаров
item_item_sim_matrix = cos_sim(m)
item_item_sim_matrix

In [ ]:
# Добавляем название столбцов и индексов в матрицу мер близости между векторами-строками покупателей
item_item_sim_matrix = pd.DataFrame(item_item_sim_matrix)

item_item_sim_matrix.columns = item_customer_matrix.index

item_item_sim_matrix['StockCode'] = item_customer_matrix.index
item_item_sim_matrix = item_item_sim_matrix.set_index('StockCode')

item_item_sim_matrix.head()

In [ ]:
# На примере товара находим те товары, которые близки к нему по косинусной мере
top_10_similar_items = item_item_sim_matrix.loc[23166].sort_values(ascending=False).iloc[1:11].index
top_10_similar_items

In [ ]:
df[df['StockCode'] == 23166].drop_duplicates('StockCode')[['StockCode', 'Description']]

In [ ]:
df[df['StockCode'].isin(top_10_similar_items)][['StockCode', 'Description']].drop_duplicates().set_index('StockCode').loc[top_10_similar_items]